import { useState } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, Chrome, LoaderCircle, LockKeyhole } from 'lucide-react';
import { useAuth } from '../auth/AuthContext';
import { PageHero } from './GenericProfessional';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';
function AuthShell({ children, title, copy }) { return <><PageHero eyebrow="Client portal" title={title} copy={copy} /><section className="section auth-section"><div className="auth-card">{children}</div></section></>; }
function ErrorMessage({ error }) { if (!error) return null; const messages = { google_auth_failed: 'Google sign-in could not be completed. Please try again.', google_state_invalid: 'The sign-in session expired. Please try again.', google_email_unverified: 'Google could not confirm your email address.', account_inactive: 'This account is not active. Please contact Tervoxa.' }; return <div className="form-error">{messages[error] || error}</div>; }

export function Login() { const { user, loading, login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(new URLSearchParams(location.search).get('error') || ''); const [busy, setBusy] = useState(false); if (!loading && user) return <Navigate to={user.role === 'admin' ? '/admin' : (location.state?.from || '/dashboard')} replace />; const submit = async event => { event.preventDefault(); setBusy(true); setError(''); try { const signedIn = await login(form); navigate(signedIn.role === 'admin' ? '/admin' : '/dashboard', { replace: true }); } catch (err) { setError(err.message); } finally { setBusy(false); } }; return <AuthShell title="Secure access to your Dashboard." copy="Sign in to review project submissions, follow progress and keep communication in one place."><div className="auth-heading"><LockKeyhole /><div><h2>Sign in to your account</h2><p>Use your business email or continue with Google.</p></div></div><a className="google-login" href={`${API_URL}/api/auth/google`}><Chrome size={18} /> Continue with Google</a><div className="auth-divider"><span>or continue with email</span></div><form className="auth-form" onSubmit={submit}><label>Business email address<input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label>Password<input required type="password" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /></label><ErrorMessage error={error} /><button className="button" disabled={busy}>{busy ? <><LoaderCircle className="spin" />Signing in...</> : <>Sign in <ArrowRight size={18} /></>}</button></form><p className="auth-switch">Do not have an account? <Link to="/register">Create a company account</Link></p></AuthShell>; }

export function Register() { const { user, loading, register } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ fullName: '', companyName: '', email: '', phone: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); if (!loading && user) return <Navigate to="/dashboard" replace />; const submit = async event => { event.preventDefault(); setBusy(true); setError(''); try { await register(form); navigate('/dashboard', { replace: true }); } catch (err) { setError(err.message); } finally { setBusy(false); } }; return <AuthShell title="Create your company account." copy="Set up a secure Dashboard for project requests, delivery updates and ongoing communication with Tervoxa Technologies."><div className="auth-heading"><LockKeyhole /><div><h2>Register your organisation</h2><p>Use a business email so your project team can stay informed.</p></div></div><a className="google-login" href={`${API_URL}/api/auth/google`}><Chrome size={18} /> Sign up with Google</a><div className="auth-divider"><span>or register with email</span></div><form className="auth-form" onSubmit={submit}><div className="form-row"><label>Full name<input required value={form.fullName} onChange={event => setForm({ ...form, fullName: event.target.value })} /></label><label>Company / organisation name<input required value={form.companyName} onChange={event => setForm({ ...form, companyName: event.target.value })} /></label></div><div className="form-row"><label>Business email address<input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label>Phone number<input required value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /></label></div><label>Create a password<input required minLength="8" type="password" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /><small>Use at least 8 characters, including a letter and a number.</small></label>{error && <div className="form-error">{error}</div>}<button className="button" disabled={busy}>{busy ? <><LoaderCircle className="spin" />Creating account...</> : <>Create account <ArrowRight size={18} /></>}</button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></AuthShell>; }

export function ProtectedRoute({ children, role }) { const { user, loading } = useAuth(); if (loading) return <div className="route-loading">Loading your Dashboard...</div>; if (!user) return <Navigate to="/login" replace />; if (role && user.role !== role) return <Navigate to={user.role === 'admin' ? '/admin' : '/dashboard'} replace />; return children; }
