import { Link } from 'react-router-dom';
import { ArrowRight, BriefcaseBusiness, Code2, ShieldCheck, Users } from 'lucide-react';
import { Audience, FinalCTA, Process, SectionHead, ServicesPreview, Values, Why } from '../components/SectionsProfessional';

export default function HomeProfessional() { return <>
  <section className="hero"><div className="hero-grid" /><div className="container hero-inner"><div className="hero-copy"><span className="eyebrow">TERVOXA TECHNOLOGIES</span><h1>Technology.<br /><em>Vision. Value.</em></h1><h2>We build the digital tools your business needs.</h2><p>From a new website to custom software, security work or technical drawings, we help turn a clear business need into work you can use.</p><div className="hero-actions"><Link className="button" to="/services">See what we deliver <ArrowRight size={18} /></Link><Link className="button ghost" to="/contact">Submit a project enquiry</Link></div><div className="hero-note"><b>Build. Protect. Support.</b><span>One team for technology, security, business and design</span></div></div><div className="hero-visual"><div className="orb orb-a" /><div className="orb orb-b" /><div className="logo-stage"><img src="/tervoxa-mark.jpeg" alt="Tervoxa Technologies T-V mark" /><div className="stage-label">TECHNOLOGY / VISION / VALUE</div></div></div></div></section>
  <section className="section integrated"><div className="container"><SectionHead eyebrow="What we do" title="The right capability for the job." copy="No two projects start in the same place. Our emblem captures how we connect the right expertise to the outcome your business needs."/><div className="emblem-story"><div className="emblem-story-mark"><img src="/tervoxa-emblem.png" alt="Tervoxa Technologies emblem showing technology, security, growth and people" /></div><div className="emblem-story-copy"><p className="emblem-lead">Technology connects people, protects businesses and enables growth.</p><div className="emblem-meaning-grid"><div><Code2 /><div><b>Build</b><span>Technology and innovation that turn practical requirements into useful digital solutions.</span></div></div><div><ShieldCheck /><div><b>Protect</b><span>Security and trust built into the systems, data and digital assets businesses rely on.</span></div></div><div><BriefcaseBusiness /><div><b>Grow</b><span>Business-focused work that improves efficiency and creates a stronger path forward.</span></div></div><div><Users /><div><b>Support</b><span>People, collaboration and dependable partnerships that keep progress moving.</span></div></div></div><p className="emblem-close">At the centre, the X represents connected expertise: technology, security, business and people working together rather than in isolation.</p></div></div></div></section>
  <section className="section about-teaser"><div className="container split"><div className="about-teaser-lead"><span className="eyebrow">About Tervoxa</span><h2>A technology partner for the work behind the business.</h2><div className="about-points"><div><b>01</b><span>Listen to the situation</span></div><div><b>02</b><span>Agree what needs to be done</span></div><div><b>03</b><span>Deliver and support the result</span></div></div></div><div className="about-teaser-copy"><p>Tervoxa Technologies works with businesses, organisations, professionals and individuals on digital, technical and security projects.</p><p>We keep the first conversation straightforward: what is happening today, what needs to improve and what would make the project worthwhile.</p><Link className="text-link" to="/about">Learn how we work <ArrowRight size={16} /></Link></div></div></section>
  <ServicesPreview /><Why /><Process /><Values /><Audience /><FinalCTA />
</>; }
