import {Link} from 'react-router-dom';import {ArrowRight,ShieldCheck,Workflow,Code2,Smartphone,Boxes,PenTool,CheckCircle2} from 'lucide-react';import {services,process,values,audiences} from '../data/content';
const icons=[Code2,Smartphone,Boxes,ShieldCheck,Workflow,PenTool];
export function SectionHead({eyebrow,title,copy}){return <div className="section-head"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
export function ServicesPreview(){return <section className="section"><div className="container"><SectionHead eyebrow="Six capabilities" title="Technology & Business Solutions Under One Roof" copy="An integrated approach across technology, security, business and design, shaped around individual project requirements."/><div className="service-grid">{services.map((s,i)=>{let I=icons[i];return <Link className="service-card" to={'/services/'+s.slug} key={s.slug}><div className="card-top"><span>{s.num}</span><I/></div><h3>{s.title}</h3><p>{s.short}</p><span className="learn">Explore service <ArrowRight size={16}/></span></Link>})}</div></div></section>}
export function Why(){let data=[['Requirement-Focused','We begin by understanding the actual requirement instead of applying the same solution to every project.'],['Customized Solutions','Our services can be adapted according to the size, scope and objectives of each project.'],['Technology-Focused','We work across web, mobile, software and cybersecurity to provide technology-oriented solutions.'],['Security-Aware','Security considerations are incorporated where relevant to the project and its requirements.'],['Business Understanding','We consider the business purpose behind a technology project, not only its technical implementation.'],['Clear Communication','We aim to keep project scope, requirements, development stages and deliverables clearly communicated.'],['Long-Term Approach','Our solutions can be planned with future updates, maintenance and scalability in mind where applicable.']];return <section className="section dark"><div className="container"><SectionHead eyebrow="Why Tervoxa Technologies?" title="Practical Solutions. Clear Approach."/><div className="why-grid">{data.map((x,i)=><div className="why-item" key={x[0]}><span>0{i+1}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div></div>)}</div></div></section>}
export function Process(){return <section className="section process-section"><div className="container"><SectionHead eyebrow="Our Working Process" title="From Requirement to Solution" copy="A connected journey from understanding the requirement through delivery and support."/><div className="timeline">{process.map((x,i)=><div className="step" key={x[0]}><div className="step-num">0{i+1}</div><div><h3>{x[0]}</h3><p>{x[1]}</p></div></div>)}</div></div></section>}
export function Values(){return <section className="section soft"><div className="container"><SectionHead eyebrow="What Guides Us" title="Core Values"/><div className="value-grid">{values.map((v,i)=><div className="value" key={v[0]}><CheckCircle2/><h3>{v[0]}</h3><p>{v[1]}</p></div>)}</div></div></section>}
export function Audience(){return <section className="section"><div className="container"><SectionHead eyebrow="Who We Serve" title="Solutions For Different Requirements" copy="Our services can be suitable for a range of businesses, organizations, professionals and individuals."/><div className="audience-grid">{audiences.map((a,i)=><div key={a}><span>0{i+1}</span>{a}</div>)}</div></div></section>}
export function FinalCTA(){return <section className="final-cta"><div className="container"><span className="eyebrow">Start a conversation</span><h2>Have an Idea? Let's Build It.</h2><p>Your requirement may start with a simple idea, a business problem or a need for a better digital solution.</p><p>Tervoxa Technologies helps transform requirements into practical technology, security, business and design solutions.</p><strong>Build. Protect. Support.</strong><Link className="button light" to="/contact">Get in Touch <ArrowRight size={18}/></Link></div></section>}
