import { Link } from 'react-router-dom';
import { ArrowRight, Boxes, CheckCircle2, Code2, PenTool, ShieldCheck, Smartphone, Workflow } from 'lucide-react';
import { audiences, process, services, values } from '../data/contentProfessional';

const icons = [Code2, Smartphone, Boxes, ShieldCheck, Workflow, PenTool];
export function SectionHead({ eyebrow, title, copy }) { return <div className="section-head"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>; }
export function ServicesPreview() { return <section className="section"><div className="container"><SectionHead eyebrow="What we deliver" title="Start with the work you need done." copy="Choose one area or bring us a larger brief. We will help define the scope and the right way to deliver it." /><div className="service-grid">{services.map((service, index) => { const Icon = icons[index]; return <Link className="service-card" to={`/services/${service.slug}`} key={service.slug}><div className="card-top"><span>{service.num}</span><Icon /></div><h3>{service.title}</h3><p>{service.short}</p><span className="learn">View capability <ArrowRight size={16} /></span></Link>; })}</div></div></section>; }
export function Why() { const data = [['We listen first', 'We start with the situation you are in, not with a package we are trying to sell.'], ['The scope stays visible', 'You know what is included, what is not and what decisions are still needed.'], ['The right people are involved', 'We bring technology, security, business and design into the conversation when the work calls for it.'], ['Security is handled responsibly', 'Assessments and testing are carried out with the right authorisation and care.'], ['The result has to be usable', 'The finished work should make sense to the people who use and maintain it.'], ['You get a straight answer', 'We keep communication clear, including when a different approach would be better.'], ['The work can continue', 'Where useful, we plan for updates, maintenance and the next stage after delivery.']]; return <section className="section dark"><div className="container"><SectionHead eyebrow="What you can expect" title="A straightforward way to work together"/><div className="why-grid">{data.map((item, index) => <div className="why-item" key={item[0]}><span>0{index + 1}</span><div><h3>{item[0]}</h3><p>{item[1]}</p></div></div>)}</div></div></section>; }
export function Process() { return <section className="section process-section"><div className="container"><SectionHead eyebrow="How a project moves forward" title="From the first conversation to delivery" copy="We keep the stages clear so you always know where the work stands and what happens next."/><div className="timeline">{process.map((item, index) => <div className="step" key={item[0]}><div className="step-num">0{index + 1}</div><div><h3>{item[0]}</h3><p>{item[1]}</p></div></div>)}</div></div></section>; }
export function Values() { return <section className="section soft"><div className="container"><SectionHead eyebrow="How we work" title="The standards we bring to every project"/><div className="value-grid">{values.map(value => <div className="value" key={value[0]}><CheckCircle2 /><h3>{value[0]}</h3><p>{value[1]}</p></div>)}</div></div></section>; }
export function Audience() { return <section className="section"><div className="container"><SectionHead eyebrow="Who we work with" title="For the people responsible for getting something done" copy="We work with founders, business teams, professionals, organisations and individuals who need a clear digital or technical outcome."/><div className="audience-grid">{audiences.map((audience, index) => <div key={audience}><span>{String(index + 1).padStart(2, '0')}</span>{audience}</div>)}</div></div></section>; }
export function FinalCTA() { return <section className="final-cta"><div className="container"><span className="eyebrow">Start a project</span><h2>Tell us what you are trying to achieve.</h2><p>Bring us a new idea, an existing process, a security concern or technical work that needs a dependable next step.</p><strong>Build. Protect. Support.</strong><Link className="button light" to="/contact">Submit a project enquiry <ArrowRight size={18} /></Link></div></section>; }
